export const REGISTRADO_SUCESSO = "REGISTRADO_SUCESSO";
export const FALHA_REGISTRO = "FALHA_REGISTRO";
export const USUARIO_CARREGADO = "USUARIO_CARREGADO";
export const AUTH_ERRO = "AUTH_ERRO";
export const LOGIN_SUCESSO = "LOGIN_SUCESSO";
export const LOGIN_FALHA = "LOGIN_FALHA";
export const LOGOUT = "LOGOUT";
export const LIMPA_ERROS = "LIMPA_ERROS";

export const SET_ALERTA = "SET_ALERTA";
export const REMOVE_ALERTA = "REMOVE_ALERTA";

export const GET_BAIXASAAGENDAS = "GET_BAIXASAAGENDAS";
export const BAIXASAAGENDAS_ERROR = "BAIXASAAGENDAS_ERROR";
export const ATUALIZA_BAIXASAAGENDAS = "ATUALIZA_BAIXASAAGENDAS";
export const ATUALIZA_BAIXASAAGENDAS_ERROR = "ATUALIZA_BAIXASAAGENDAS_ERROR";

export const FILTRA_BAIXASAAGENDAS = "FILTRA_BAIXASAAGENDAS";
export const ATUALIZA_BAIXASAAGENDASFILTRADAS =
  "ATUALIZA_BAIXASAAGENDASFILTRADAS";

export const LIMPA_FILTRO_BAIXASAAGENDAS = "LIMPA_FILTRO_BAIXASAAGENDAS";

export const SET_LOADING = "SET_LOADING";

export const GET_FILIAIS = "GET_FILIAIS";
export const GET_FILIAIS_ERROR = "GET_FILIAIS_ERROR";
export const SET_LOADING_FILIAIS = "SET_LOADING_FILIAIS";
export const LIMPA_ERROS_FILIAIS = "LIMPA_ERROS_FILIAIS";
